### ISSUE TITLE
Naval mines crash my game

### ISSUE THREAD

**Issue by aPotatoGod** [Ladysnake/BLAST#47]
[21:52:13] [Render thread/ERROR]:
 Reported exception thrown!
net.minecraft.class_148: Rendering entity in world
	at net.minecraft.class_898.method_3954(class_898.java:176) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_761.method_22977(class_761.java:1574) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_761.method_22710(class_761.java:1324) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_757.method_3188(class_757.java:1110) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_757.method_3192(class_757.java:880) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.22.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551) ~[quilt-loader-0.22.0.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84) ~[quilt-loader-0.22.0.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.22.0.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null
	at me.pepperbell.continuity.impl.client.ProcessingContextImpl.<init>(ProcessingContextImpl.java:18) ~[continuity-3.0.0-beta.41.20.1.i0:0/:?]
	at me.pepperbell.continuity.client.model.CTMBakedModel$CTMQuadTransform.<init>(CTMBakedModel.java:83) ~[continuity-3.0.0-beta.41.20.1.i0:0/:?]
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.<init>(ModelObjectsContainer.java:10) ~[continuity-3.0.0-beta.41.20.1.i0:0/:?]
	at java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305) ~[?:?]
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195) ~[?:?]
	at java.lang.ThreadLocal.get(ThreadLocal.java:172) ~[?:?]
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.get(ModelObjectsContainer.java:18) ~[continuity-3.0.0-beta.41.20.1.i0:0/:?]
	at me.pepperbell.continuity.impl.client.ContinuityFeatureStatesImpl.get(ContinuityFeatureStatesImpl.java:16) ~[continuity-3.0.0-beta.41.20.1.i0:0/:?]
	at me.pepperbell.continuity.api.client.ContinuityFeatureStates.get(ContinuityFeatureStates.java:10) ~[continuity-3.0.0-beta.41.20.1.i0:0/:?]
	at net.minecraft.class_901.handler$znp000$continuity$beforeRenderModel(class_901.java:518) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_901.method_3965(class_901.java:45) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_901.method_3936(class_901.java:17) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_898.method_3954(class_898.java:145) ~[minecraft-1.20.1.i0:0/:?]
	... 14 more
	
	
	
	full log here: https://api.mclo.gs/1/raw/230Gm6l

**Comment by EvieTheOwl** [comment]
Check if u have Sodium + Indium installed and maybe remove https://modrinth.com/mod/continuity
