### ISSUE TITLE
Stripminer fails to exist

### ISSUE THREAD

**Issue by Derpford** [Ladysnake/BLAST#6]
When I go to detonate a stripminer on 1.16.2 with BLAST version 1.4, this error pops:
```
[01:03:51] [Server thread/FATAL]: Error executing task on Server
java.lang.IllegalArgumentException: Duplicate id value for 8!
	at net.minecraft.class_2945.method_12784(class_2945.java:80) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at ladysnake.blast.common.entities.StripminerEntity.method_5693(StripminerEntity.java:31) ~[blast-1.4.jar:?]
	at net.minecraft.class_1297.<init>(class_1297.java:260) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_1676.<init>(class_1676.java:24) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_1682.<init>(class_1682.java:20) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_3857.<init>(class_3857.java:18) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at ladysnake.blast.common.entities.BombEntity.<init>(BombEntity.java:26) ~[blast-1.4.jar:?]
	at ladysnake.blast.common.entities.StripminerEntity.<init>(StripminerEntity.java:24) ~[blast-1.4.jar:?]
	at net.minecraft.class_1299.method_5883(class_1299.java:463) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at ladysnake.blast.common.block.StripminerBlock.primeStripminer(StripminerBlock.java:99) ~[blast-1.4.jar:?]
	at ladysnake.blast.common.block.StripminerBlock.method_9534(StripminerBlock.java:113) ~[blast-1.4.jar:?]
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:894) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_3225.method_14262(class_3225.java:328) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_3244.method_12046(class_3244.java:972) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_2885.method_12547(class_2885.java:36) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_2885.method_11054(class_2885.java:10) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:758) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:152) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:740) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:734) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:719) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
```

**Comment by doctor4t** [comment]
But do you have this issue with 1.16.3?

**Comment by Derpford** [comment]
I haven't tested on 1.16.3, so it might just be that there's not a 1.16.2 version available right now. Several other mods that I want are still on 1.16.2, so I haven't pushed past that version.

**Comment by LeFauxMatt** [comment]
I'm having this same issue on my 1.16.3 server (playing the latest version of AOF3)
https://gist.github.com/ImJustMatt/4537983aa7a25131f1c05f789bf0f3bc
```[02:21:22] [Server thread/FATAL]: Error executing task on Server
java.lang.IllegalArgumentException: Duplicate id value for 8!
	at net.minecraft.class_2945.method_12784(class_2945.java:80) ~[intermediary-server.jar:?]
	at ladysnake.blast.common.entities.StripminerEntity.method_5693(StripminerEntity.java:31) ~[blast-1.4.jar:?]
	at net.minecraft.class_1297.<init>(class_1297.java:260) ~[intermediary-server.jar:?]
	at net.minecraft.class_1676.<init>(class_1676.java:24) ~[intermediary-server.jar:?]
	at net.minecraft.class_1682.<init>(class_1682.java:20) ~[intermediary-server.jar:?]
	at net.minecraft.class_3857.<init>(class_3857.java:18) ~[intermediary-server.jar:?]
	at ladysnake.blast.common.entities.BombEntity.<init>(BombEntity.java:26) ~[blast-1.4.jar:?]
	at ladysnake.blast.common.entities.StripminerEntity.<init>(StripminerEntity.java:24) ~[blast-1.4.jar:?]
	at net.minecraft.class_1299.method_5883(class_1299.java:463) ~[intermediary-server.jar:?]
	at ladysnake.blast.common.block.StripminerBlock.primeStripminer(StripminerBlock.java:99) ~[blast-1.4.jar:?]
	at ladysnake.blast.common.block.StripminerBlock.method_9534(StripminerBlock.java:113) ~[blast-1.4.jar:?]
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:894) ~[intermediary-server.jar:?]
	at net.minecraft.class_3225.redirect$chg000$activateWithOptionalCactus(class_3225.java:6029) ~[intermediary-server.jar:?]
	at net.minecraft.class_3225.method_14262(class_3225.java:328) ~[intermediary-server.jar:?]
	at net.minecraft.class_3244.method_12046(class_3244.java:972) ~[intermediary-server.jar:?]
	at net.minecraft.class_2885.method_12547(class_2885.java:36) ~[intermediary-server.jar:?]
	at net.minecraft.class_2885.method_11054(class_2885.java:10) ~[intermediary-server.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:758) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:152) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:740) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:734) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:719) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.handler$ceo000$modifiedRunLoop(MinecraftServer.java:11806) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:648) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

This occurs as I'm trying to activate the Stripminer. It just disappears with that error message. After the second time, I tried placing a block in the spot where the Stripminer had been and it returned the two back to me.

**Comment by doctor4t** [comment]
I can't seem to be able to reproduce this error, so maybe it's a mod incompatibility? But I don't see anything that suggests one. Do you maybe have more instructions on how to reproduce it? 🤔

**Comment by LeFauxMatt** [comment]
I recorded a video on what exactly happens. Not much to it https://youtu.be/ay02Td36p_k

**Comment by dandin87** [comment]
This also happens in the All Of Fabric 3 modpack, if that makes it easier for you to test. I honestly have no idea which mod would be causing a conflict with yours. I might try to track it down this weekend though.
